= Library for managing CBA9 Banknote Validators

image:https://img.shields.io/github/v/tag/ingonoka/cba9-driver?label=Latest[GitHub tag (latest by date)]

The library is meant for Android devices that are connected via USB to a CBA9 banknote validator.

The validator is expected to be configured for the SSP(TM) protocol (the device supports other protocols as well).

== Limitation
The library does not support the optional encryption provided in the SSP(TM) protocol.

== Setup

=== Software
Include the latest library version in your `gradle.build` dependency block

[source,Groovy]
.Replace the `latest` placeholder with the latest release version
----
implementation "com.ingonoka:cba9-driver:<latest>"
----

=== Hardware

The CBA9 is a banknote acceptor manufactured by https://www.innovative-technology.com[Innovate Technology] for the Asian market. The device comes with a technical handbook that gives details on power and data connection as well as hardware setup. The handbook also explains how to configure the device for the SSP(TM) protocol.

The CBA9 must be connected via an OTG cable to the Android device.

The problem is that most Android devices will not charge the device when in USB OTG mode. Usually, the provider of the Android device can change this default behaviour. The OTG cable will also likely have to be altered to get the power for charging from a separate charger.

Of course the BNA cannot get its power from the Android device and will also need a separate connection for power.



== Usage

=== Configuration of the CBA9 Driver Factory

Before starting the USB device manager, which will create and attach a driver to a connected CBA, set the configuration that will be applied to newly created drivers.

The configuration is set by changing the `stateLog` and `cba9Props` properties of the `Cba9Factory`.

This can be done also when the USB device manager is already running, but changes will only take effect when the CBA9 is disconnected and then reconnected again.

[source,kotling,indent=0]
.Sample configuration setting
----
/**
 * Example for changing state log for newly created driver to a Room
 * based log
 */
Cba9Factory.stateLog = roomCba9StateLog(this)

/**
 * Example for changing properties of CBA9 driver to limiting accepted
 * banknotes to 20 and 100 Pesos
 */
Cba9Factory.cba9Props = Cba9Factory.cba9Props.copy(
    acceptedDenominations = listOf(
        Denomination(20, CountryCode.PHP),
        Denomination(100, CountryCode.PHP)
    )
)

/**
 * Example for changing USB properties for newly created CBA9 driver
 */
Cba9Factory.cba9Props = Cba9Factory.cba9Props.copy(
    usbProps = Cba9Factory.cba9Props.usbProps.copy(
        timeoutReceive = 3.seconds
    )
)
----

=== Start USB Device Manager

CBA9 drivers are instantiated by the USB device manager. Once the USB device manager has been started, it will attempt to create and attach a driver for a CBA9 that is already connected or that will be connected (plugged-in) later.

TIP The `logcat` may show an error for an already connected device,  but usually the second attempt to attach a driver will succeed.

[source,kotlin,indent=0]
.Start of the USB device manager
----
val usbManager = UsbDeviceManager()
usbManager.start(this)
----

=== Monitor Driver Connection and Disconnection Events

You need to collect the `connectedDrivers` state flow to get the CBA9 driver. This state flow holds a list of connected drivers. A driver is added to the list of connected drivers for a newly connected CBA9, and removed when the CBA9 is disconnected.

The CBA0 driver provides access to actual validator object in a state flow. The application has to wait for the validator object to be published  before it can communicate to the device (see <<Use the CBA Validator>>).

[source,kotlin,indent=0]
.Sample monitoring of CBA9 connections
----
private fun monitorConnectedDrivers(usbManager: UsbDeviceManager, binding: ActivityMainBinding) =

    lifecycleScope.launch {

        usbManager.connectedDrivers.collect { drivers ->
            if (drivers.isNotEmpty()) {

                logger.info("List of connected drivers changed")

                usbManager.getDriver(Cba9::class)
                    .onSuccess { /* New CBA9 connection */ }
                    .onFailure { /* Some other device was connected or CBA9 was lost */ }

            }
        }
    }
----

=== Use the CBA Validator

==== Monitor the validator status

The `state` flow of the validator provides information about the current status, such as whether the validator is scanning/stacking/rejecting a banknote or whether a banknote is currently in escrow.

[source,kotlin,indent=0]
.Sample monitoring of validator object provided by the driver
----
/* cba9 is a driver provided by the connected Drivers flow of the USB device manager */
cba9.cba9Validator.filterNotNull().collect { iCba9Validator ->
    iCba9Validator.state.collect { stateHolder ->
       when (stateHolder.state) {
            Cba9ValidatorState.UNDEFINED -> TODO()
            Cba9ValidatorState.DISCONNECTED -> TODO()
            Cba9ValidatorState.FAILURE -> TODO()
            Cba9ValidatorState.INITIALIZING -> TODO()
            Cba9ValidatorState.SCANNING -> TODO()
            Cba9ValidatorState.NOTE_IN_ESCROW -> TODO()
            Cba9ValidatorState.REJECTING -> TODO()
            Cba9ValidatorState.STACKING -> TODO()
            Cba9ValidatorState.STACKING_CREDITED -> TODO()
            Cba9ValidatorState.READY -> TODO()
            Cba9ValidatorState.UNSAFE_JAM -> TODO()
            Cba9ValidatorState.DISABLED -> TODO()
            Cba9ValidatorState.INHIBITED -> TODO()
            Cba9ValidatorState.CASHBOX_FULL -> TODO()
       }
    }
}
----

If a banknote is in escrow, the validator will hold it there. The application can instruct the validator to reject or accept the banknote by calling `rejectBanknote()` or `acceptBanknote()`. If either function is called when no banknote is in escrow, then the banknote will be immediately rejected or accepted when it enters into escrow.



==== Monitor cashbox fill levels

The validator object contains a cashbox property which manages a fill level state flow.  Collect the `levels` state flow to get the latest fill levels of the banknote acceptor.

[source,kotlin,indent=0]
.Sample monitoring of the cashbox state
----
private fun updateCba9FillLevel(cba9: Cba9, binding: ActivityMainBinding) =
    lifecycleScope.launch {

    cba9.cba9Validator.filterNotNull().collect {
        val currency = it.configData.countryCode

        it.cashbox.levels.collect { levelHolder ->

            binding.textViewFillLevelValue.text =
                getString(
                    R.string.fillLevel,
                    currency.countryCode,
                    levelHolder.banknoteValue,
                    levelHolder.banknoteCount
                )
        }
    }
}
----