= Library for managing CBA9 Banknote Validators

image:https://img.shields.io/github/v/tag/ingonoka/cba9-driver?label=Latest[GitHub tag (latest by date)]

The library is meant for Android devices that are connected via USB to a CBA9 banknote validator.

The validator is expected to support the SSP(TM) protocol.

== Setup
Include the latest library version in your `gradle.build` dependency block

[source,Groovy]
.Replace the `latest` placeholder with the latest release version
----
implementation "com.ingonoka:cba9-driver:latest"
----

== Usage

=== Configuration of the CBA9 Driver Factory

Before starting the USB device manager, which will create and attach a driver to a connected CBA, set the configuration of newly created drivers, by changing the `stateLog` and `cba9Props` properties of the `Cba9Factory`.

This can be done also when the USB device manager is already running, but changes will only take effect when the CBA9 is disconnected and then reconnected again.

[source,kotling,indent=0]
----
/**
 * Example for changing state log for newly created driver to a Room
 * based log
 */
Cba9Factory.stateLog = roomCba9StateLog(this)

/**
 * Example for changing properties of CBA9 driver to limiting accepted
 * banknotes to 20 and 100 Pesos
 */
Cba9Factory.cba9Props = Cba9Factory.cba9Props.copy(
    acceptedDenominations = listOf(
        Denomination(20, CountryCode.PHP),
        Denomination(100, CountryCode.PHP)
    )
)

/**
 * Example for changing USB properties for newly created CBA9 driver
 */
Cba9Factory.cba9Props = Cba9Factory.cba9Props.copy(
    usbProps = Cba9Factory.cba9Props.usbProps.copy(
        timeoutReceive = 3.seconds
    )
)
----

=== Start USB Device Manager

Once the USB device manager has been started, it will attempt to attach a driver for a CBA9 that is already connected or that is connected (plugged-in) later.

TIP The `logcat` may show an error for an already connected device,  but usually the second attempt to attach a driver will succeed.

[source,kotlin,indent=0]
----
val usbManager = UsbDeviceManager()
usbManager.start(this)
----

=== Monitor Driver Connection and Disconnection Events

Collect the `connectedDrivers` state flow to get the CBA9 driver. The driver is added to the list of connected drivers for a newly connected CBA9, and removed when the CBA9 is disconnected.

The actual validator object is provided in a state flow managed by the driver.

IMPORTANT
The validator object will not be immediately available when the driver is published in the `connectedDrivers` state flow (see <<Use the CBA Validator>>)

[source,kotlin,indent=0]
----
private fun monitorConnectedDrivers(usbManager: UsbDeviceManager, binding: ActivityMainBinding) =

    lifecycleScope.launch {
        var configUpdater: Job? = null
        var statusUpdater: Job? = null

        usbManager.connectedDrivers.collect { drivers ->
            if (drivers.isNotEmpty()) {
                logger.info("Connected drivers: ${drivers.joinToString { it.preferredName }}")

                usbManager.getDriver(Cba9::class)
                    .onSuccess { configUpdater = updateCba9ConfigData(it, binding) }
                usbManager.getDriver(Cba9::class)
                    .onSuccess { statusUpdater = updateCba9Status(it, binding) }

            } else {

                configUpdater?.cancelAndJoin()
                statusUpdater?.cancelAndJoin()
            }
        }
    }
----

=== Use the CBA Validator

==== Monitor the validator status

The `state` flow of the validator provides information about the current status, such as whether the validator is scanning/stacking/rejecting a banknote or whether a banknote is currently in escrow.

[source,kotlin,indent=0]
----
cba9.cba9Validator.filterNotNull().collect { iCba9Validator ->
    iCba9Validator.state.collect { stateHolder ->
       when (stateHolder.state) {
            Cba9ValidatorState.UNDEFINED -> TODO()
            Cba9ValidatorState.DISCONNECTED -> TODO()
            Cba9ValidatorState.FAILURE -> TODO()
            Cba9ValidatorState.INITIALIZING -> TODO()
            Cba9ValidatorState.SCANNING -> TODO()
            Cba9ValidatorState.NOTE_IN_ESCROW -> TODO()
            Cba9ValidatorState.REJECTING -> TODO()
            Cba9ValidatorState.STACKING -> TODO()
            Cba9ValidatorState.STACKING_CREDITED -> TODO()
            Cba9ValidatorState.READY -> TODO()
            Cba9ValidatorState.UNSAFE_JAM -> TODO()
            Cba9ValidatorState.DISABLED -> TODO()
            Cba9ValidatorState.INHIBITED -> TODO()
            Cba9ValidatorState.CASHBOX_FULL -> TODO()
       }
    }
}
----


==== Monitor cashbox fill levels

The validator object contains a cashbox property which manages a fill level state flow.  Collect the `levels` state flow to get the latest fill levels of the banknote acceptor.

[source,kotlin,indent=0]
----
private fun updateCba9FillLevel(cba9: Cba9, binding: ActivityMainBinding) =
    lifecycleScope.launch {

    cba9.cba9Validator.filterNotNull().collect {
        val currency = it.configData.countryCode

        it.cashbox.levels.collect { levelHolder ->

            binding.textViewFillLevelValue.text =
                getString(
                    R.string.fillLevel,
                    currency.countryCode,
                    levelHolder.banknoteValue,
                    levelHolder.banknoteCount
                )
        }
    }
}
----