/*
 * Copyright (c) 2022. Ingo Noka
 * This file belongs to project load-kiosk.
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
 * Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 *
 */

package com.ingonoka.cba9driver.event

import com.ingonoka.cba9driver.data.CountryCode
import com.ingonoka.cba9driver.data.Denomination

/**
 * An META event generated by the driver when receiving a read event with channel set to 0. This means the
 * device is busy scanning but has not yet determined the denomination of the banknote.
 */
class Scanning : Read(Denomination(0, CountryCode.UNKNOWN)) {

    override fun stringify(short: Boolean, indent: String): String =
        if (short) {
            "Scanning"
        } else {
            "Scanning banknote."
        }
}